# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - llmlegal4

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://2de68ddb1fe84c3fa319be865776e250.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_9794b25867fd43eba1e8194ae7bc259a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_acb2b22f73544eabb5970842b154332b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: 2de68ddb1fe84c3fa319be865776e250.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9794b25867fd43eba1e8194ae7bc259a }}/llmlegal4image:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'llmlegal4'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f996d23a08144db496cc18d17c4b9e70 }}
        images: '2de68ddb1fe84c3fa319be865776e250.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9794b25867fd43eba1e8194ae7bc259a }}/llmlegal4image:${{ github.sha }}'